# version: '3.3'
# services:
#   web:
#     build:
#       context: ./
#     volumes:
#       - .:/src
#     command: supervisor -e  '.' index.js
#     # command: supervisor -e  'js,pug,html' index.js, this is the tutors own
#     ports:
#       - "3000:3000"
#     depends_on:
#       - db
#   db:
#     image: mysql
#     restart: always
#     env_file:
#       - ./.env
#     ports:
#       - "3308:3306"
#     volumes:
#       - ./db:/var/lib/mysql
#   phpmyadmin:
#     image: phpmyadmin/phpmyadmin:latest
#     restart: always
#     env_file:
#       - ./.env
#     ports:
#       - "8081:80"



version: "3.3"
services:
 web:
  build:
   context: .
  volumes:
   - ./:/app
  # command: supervisor -e  '.' index.js
  command: sh -c "sleep 15 && supervisor -e '.' index.js"
  # command: supervisor -e  'js,pug,html' index.js, this is the tutors own
  ports:
   - "3000:3000"
  depends_on:
   - db
  environment:
   - MYSQL_HOST=db
 db:
  image: mysql
  restart: always
  env_file:
   - ./.env
  environment:
   - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
   - MYSQL_DATABASE=${MYSQL_DATABASE}
   - MYSQL_USER=${MYSQL_USER}
   - MYSQL_PASS=${MYSQL_PASS}
  ports:
   - "3308:3306"
  volumes:
   - ./db:/var/lib/mysql
  healthcheck:
   test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
   interval: 10s
   timeout: 5s
   retries: 5
 phpmyadmin:
  image: phpmyadmin/phpmyadmin:latest
  restart: always
  env_file:
   - ./.env
  ports:
   - "8081:80"
